import type {
  CrossTheme,
  Decision,
  Feedback,
  Issue,
  TrendPoint,
} from "./types";

export const issues: Issue[] = [
  {
    id: "payment-timeouts",
    name: "Payment gateway timeouts at checkout",
    industry: "ecommerce",
    theme: "Payment",
    mentions: 289,
    negativePct: 94,
    trendPct: 42,
    priorityScore: 92,
    priorityLevel: "critical",
    sentiment: { positive: 2, neutral: 4, negative: 94 },
    trend: [18, 22, 26, 31, 30, 38, 44, 51, 58, 64, 72, 81, 88, 94],
    patterns: [
      "Failures cluster on card payments above £120",
      "78% of reports mention a spinning button with no error message",
      "Peaks between 19:00 and 22:00 local time",
      "Mobile web affected 3.1x more than the native app",
    ],
    whyPrioritized: [
      "Highest negative share of any cluster (94%)",
      "Directly blocks completed revenue, not just satisfaction",
      "Mentions grew 42% week over week with no plateau",
      "Spans 12 merchants, so the cause is platform-side",
    ],
    insight:
      "Checkout abandonment is being driven by a gateway retry window that is shorter than the issuer's 3-D Secure response time. Customers read the silent failure as a fraud block and rarely retry, so the loss compounds with basket value.",
    recommendedAction:
      "Extend the gateway timeout to 45s, surface an explicit retry state with the last-4 card digits, and queue failed authorisations for a single automatic retry.",
    emerging: false,
  },
  {
    id: "delivery-late",
    name: "Deliveries arriving outside the promised window",
    industry: "ecommerce",
    theme: "Delivery",
    mentions: 231,
    negativePct: 86,
    trendPct: 19,
    priorityScore: 87,
    priorityLevel: "critical",
    sentiment: { positive: 5, neutral: 9, negative: 86 },
    trend: [40, 43, 41, 47, 52, 55, 58, 57, 62, 66, 71, 74, 79, 84],
    patterns: [
      "Two-day promise missed most often in postcodes served by one carrier",
      "Tracking page still shows 'out for delivery' after the window closes",
      "Complaints double on Mondays after weekend backlogs",
    ],
    whyPrioritized: [
      "Second highest mention volume across all domains",
      "Strong overlap with refund requests in the same threads",
      "Repeat customers are 2.4x more likely to mention it",
    ],
    insight:
      "The promise shown at checkout is calculated from warehouse capacity, not carrier capacity. Customers accept slow delivery but not a broken promise, so the damage is to trust rather than speed.",
    recommendedAction:
      "Recalculate the delivery promise from live carrier SLAs per postcode and send a proactive re-promise message the moment a window is at risk.",
    emerging: false,
  },
  {
    id: "wait-times",
    name: "Wait times exceeding posted estimates",
    industry: "restaurant",
    theme: "Waiting time",
    mentions: 204,
    negativePct: 81,
    trendPct: 27,
    priorityScore: 84,
    priorityLevel: "high",
    sentiment: { positive: 6, neutral: 13, negative: 81 },
    trend: [30, 33, 36, 34, 39, 44, 48, 52, 55, 61, 64, 70, 76, 80],
    patterns: [
      "Quoted 20 minutes, actual median 41 minutes on Friday evenings",
      "Guests who were updated mid-wait left neutral, not negative, reviews",
      "Six locations account for 72% of mentions",
    ],
    whyPrioritized: [
      "Largest restaurant-side cluster by mentions",
      "Highest correlation with 1 and 2 star ratings",
      "Trend rising 27% while covers stayed flat",
    ],
    insight:
      "Guests tolerate long waits but punish inaccurate ones. The host quote is a fixed number rather than a live estimate, so every busy service creates a broken expectation at the door.",
    recommendedAction:
      "Drive the host quote from live table-turn data and push an SMS update whenever the estimate slips by more than ten minutes.",
    emerging: false,
  },
  {
    id: "order-accuracy",
    name: "Wrong or missing items in delivered orders",
    industry: "restaurant",
    theme: "Order accuracy",
    mentions: 176,
    negativePct: 88,
    trendPct: 14,
    priorityScore: 79,
    priorityLevel: "high",
    sentiment: { positive: 3, neutral: 9, negative: 88 },
    trend: [26, 28, 31, 30, 35, 37, 40, 44, 46, 50, 54, 57, 61, 65],
    patterns: [
      "Missing sides and drinks far more often than mains",
      "Concentrated on multi-item family orders",
      "Half the reports also mention a failed refund attempt",
    ],
    whyPrioritized: [
      "High negative share combined with refund cost per incident",
      "Affects the highest-value basket segment",
    ],
    insight:
      "Accuracy fails at the packing step, not the kitchen. Large orders are assembled across two stations with no single checklist, so side items silently drop out.",
    recommendedAction:
      "Print a consolidated pack checklist per order and require a scan of each bag before the courier hand-off.",
    emerging: false,
  },
  {
    id: "portion-consistency",
    name: "Inconsistent portion sizes across shifts",
    industry: "restaurant",
    theme: "Food quality",
    mentions: 149,
    negativePct: 74,
    trendPct: 9,
    priorityScore: 71,
    priorityLevel: "high",
    sentiment: { positive: 11, neutral: 15, negative: 74 },
    trend: [22, 25, 24, 27, 29, 31, 30, 34, 36, 39, 41, 44, 46, 48],
    patterns: [
      "Evening shift portions described as smaller than lunch",
      "Mentioned alongside price complaints in 61% of cases",
    ],
    whyPrioritized: [
      "Steady growth for six consecutive weeks",
      "Drives perceived value, which shows up in repeat visit intent",
    ],
    insight:
      "Guests are not comparing to a menu spec, they are comparing to their own previous visit. Variation, not size, is what reads as a price increase.",
    recommendedAction:
      "Introduce weighed portion guides for the top ten dishes and audit two services per site each week.",
    emerging: false,
  },
  {
    id: "return-flow",
    name: "Returns process unclear and slow to refund",
    industry: "ecommerce",
    theme: "Returns",
    mentions: 138,
    negativePct: 69,
    trendPct: -6,
    priorityScore: 66,
    priorityLevel: "medium",
    sentiment: { positive: 8, neutral: 23, negative: 69 },
    trend: [45, 44, 42, 43, 40, 38, 37, 36, 34, 33, 31, 30, 29, 28],
    patterns: [
      "Label generation step is where customers give up",
      "Refund expectation is 3 days, actual median is 9",
    ],
    whyPrioritized: [
      "Large volume but the trend is now falling after the label fix",
      "Still the top driver of support contacts",
    ],
    insight:
      "The policy is competitive but the process is invisible. Customers contact support to ask where their refund is because nothing confirms the parcel was received.",
    recommendedAction:
      "Send a 'we have your return' confirmation at warehouse scan and show a refund countdown in the order page.",
    emerging: false,
  },
  {
    id: "mobile-perf",
    name: "Slow mobile app load on weak connections",
    industry: "ecommerce",
    theme: "App performance",
    mentions: 121,
    negativePct: 64,
    trendPct: 22,
    priorityScore: 61,
    priorityLevel: "medium",
    sentiment: { positive: 9, neutral: 27, negative: 64 },
    trend: [15, 17, 19, 21, 20, 24, 27, 29, 33, 35, 38, 42, 45, 49],
    patterns: [
      "Product listing pages over 6s on 3G",
      "Users describe images loading one by one",
    ],
    whyPrioritized: [
      "Rising trend and a clean technical fix path",
      "Concentrated in a growth market segment",
    ],
    insight:
      "Perceived slowness comes from unbounded image payloads on category pages rather than server response time.",
    recommendedAction:
      "Ship responsive image sizes with lazy loading and a skeleton grid so the page feels complete before images settle.",
    emerging: false,
  },
  {
    id: "staff-attentiveness",
    name: "Staff attentiveness during peak service",
    industry: "restaurant",
    theme: "Service quality",
    mentions: 112,
    negativePct: 66,
    trendPct: 11,
    priorityScore: 58,
    priorityLevel: "medium",
    sentiment: { positive: 16, neutral: 18, negative: 66 },
    trend: [20, 22, 21, 24, 26, 27, 29, 31, 32, 35, 36, 38, 40, 42],
    patterns: [
      "Guests wait to flag down staff for the bill, not for food",
      "Positive mentions name individual servers, negatives name the room",
    ],
    whyPrioritized: [
      "Direct lever on tip rate and return visits",
      "Fixable with floor routing, no capital spend",
    ],
    insight:
      "The gap is at the end of the meal. Section sizes are set for the ordering phase, so the payment phase is chronically under-covered.",
    recommendedAction:
      "Add a roaming payment runner during peak and enable pay-at-table from the QR menu.",
    emerging: false,
  },
  {
    id: "loyalty-points",
    name: "Loyalty points not applying at checkout",
    industry: "restaurant",
    theme: "Payment",
    mentions: 74,
    negativePct: 71,
    trendPct: 96,
    priorityScore: 57,
    priorityLevel: "medium",
    sentiment: { positive: 6, neutral: 23, negative: 71 },
    trend: [2, 3, 4, 6, 7, 11, 14, 19, 24, 31, 38, 47, 58, 68],
    patterns: [
      "Only affects accounts created before the kiosk migration",
      "Guests notice at payment, in front of staff",
    ],
    whyPrioritized: [
      "Fastest growing cluster this period at +96%",
      "Awkward failure point that staff cannot resolve on the spot",
    ],
    insight:
      "A legacy account identifier is not being passed to the new kiosk client, so the balance exists but cannot be matched at tender time.",
    recommendedAction:
      "Backfill the legacy identifier mapping and let staff apply points manually from the terminal as an interim path.",
    emerging: true,
  },
  {
    id: "checkout-mobile-ui",
    name: "Checkout button misaligned on small screens",
    industry: "ecommerce",
    theme: "App performance",
    mentions: 61,
    negativePct: 58,
    trendPct: 212,
    priorityScore: 54,
    priorityLevel: "medium",
    sentiment: { positive: 4, neutral: 38, negative: 58 },
    trend: [1, 1, 2, 2, 3, 5, 7, 10, 15, 21, 28, 37, 48, 59],
    patterns: [
      "Appeared immediately after the 4.18 release",
      "Reported on screens narrower than 380px",
    ],
    whyPrioritized: [
      "Sharpest week-over-week rise of any cluster",
      "Sits directly on the revenue path",
    ],
    insight:
      "A sticky footer introduced in 4.18 overlaps the pay button on short viewports, so a share of mobile traffic cannot complete checkout at all.",
    recommendedAction:
      "Hotfix the safe-area inset on the checkout footer and add a small-viewport regression check to release.",
    emerging: true,
  },
  {
    id: "cold-food",
    name: "Food arriving cold on table service",
    industry: "restaurant",
    theme: "Food quality",
    mentions: 58,
    negativePct: 83,
    trendPct: 148,
    priorityScore: 52,
    priorityLevel: "medium",
    sentiment: { positive: 3, neutral: 14, negative: 83 },
    trend: [2, 2, 3, 4, 6, 8, 11, 15, 19, 25, 31, 39, 47, 55],
    patterns: [
      "Clustered in two sites since the new pass layout",
      "Mentioned with long ticket times in the same review",
    ],
    whyPrioritized: [
      "New cluster with a steep slope",
      "Strong negative share at 83%",
    ],
    insight:
      "Plates are sitting on the pass because the runner rota was cut at the same time the pass moved further from the dining room.",
    recommendedAction:
      "Restore a dedicated runner at peak in the two affected sites and add a heat-lamp dwell alert on the pass screen.",
    emerging: true,
  },
  {
    id: "packaging-damage",
    name: "Packaging damage on fragile items",
    industry: "ecommerce",
    theme: "Delivery",
    mentions: 47,
    negativePct: 61,
    trendPct: -14,
    priorityScore: 34,
    priorityLevel: "low",
    sentiment: { positive: 12, neutral: 27, negative: 61 },
    trend: [28, 27, 26, 24, 23, 22, 20, 19, 18, 17, 15, 14, 13, 12],
    patterns: [
      "Glassware and ceramics only",
      "Falling since the double-wall carton rollout",
    ],
    whyPrioritized: [
      "Low and declining volume after the packaging change",
      "Kept visible to confirm the fix holds",
    ],
    insight:
      "The carton change is working. Remaining damage is concentrated in orders that mix heavy and fragile items in one box.",
    recommendedAction:
      "Split fragile items into their own carton when total order weight exceeds 8kg.",
    emerging: false,
  },
];

export const feedback: Feedback[] = [
  {
    id: "f-1001",
    text: "Tried to pay three times and the button just spun forever. Gave up and bought it somewhere else.",
    industry: "ecommerce",
    rating: 1,
    sentiment: "negative",
    date: "2026-09-24",
    source: "Web review",
    issueIds: ["payment-timeouts"],
  },
  {
    id: "f-1002",
    text: "Card was declined on your site but worked fine everywhere else the same evening. No error shown at all.",
    industry: "ecommerce",
    rating: 1,
    sentiment: "negative",
    date: "2026-09-23",
    source: "Support ticket",
    issueIds: ["payment-timeouts"],
  },
  {
    id: "f-1003",
    text: "Checkout finally went through on the fourth attempt. Nobody should have to fight a payment screen.",
    industry: "ecommerce",
    rating: 2,
    sentiment: "negative",
    date: "2026-09-22",
    source: "App Store",
    issueIds: ["payment-timeouts", "checkout-mobile-ui"],
  },
  {
    id: "f-1004",
    text: "Promised two day delivery, arrived after six. Tracking said out for delivery for three straight days.",
    industry: "ecommerce",
    rating: 1,
    sentiment: "negative",
    date: "2026-09-24",
    source: "Web review",
    issueIds: ["delivery-late"],
  },
  {
    id: "f-1005",
    text: "Parcel was late again but at least the driver messaged me. Would still like the date to be right.",
    industry: "ecommerce",
    rating: 3,
    sentiment: "neutral",
    date: "2026-09-21",
    source: "Email survey",
    issueIds: ["delivery-late"],
  },
  {
    id: "f-1006",
    text: "Ordering was easy and the product is lovely, the delivery estimate was just wildly optimistic.",
    industry: "ecommerce",
    rating: 3,
    sentiment: "neutral",
    date: "2026-09-20",
    source: "Email survey",
    issueIds: ["delivery-late"],
  },
  {
    id: "f-1007",
    text: "Returned a jacket two weeks ago and still no refund. No confirmation that you even received it.",
    industry: "ecommerce",
    rating: 2,
    sentiment: "negative",
    date: "2026-09-19",
    source: "Support ticket",
    issueIds: ["return-flow"],
  },
  {
    id: "f-1008",
    text: "The return label step is confusing. I could not tell whether it had generated or not.",
    industry: "ecommerce",
    rating: 2,
    sentiment: "negative",
    date: "2026-09-18",
    source: "Web review",
    issueIds: ["return-flow"],
  },
  {
    id: "f-1009",
    text: "Refund came through faster than last time, so something has clearly improved.",
    industry: "ecommerce",
    rating: 4,
    sentiment: "positive",
    date: "2026-09-17",
    source: "Email survey",
    issueIds: ["return-flow"],
  },
  {
    id: "f-1010",
    text: "App takes forever to load the category pages on my commute. Images crawl in one at a time.",
    industry: "ecommerce",
    rating: 2,
    sentiment: "negative",
    date: "2026-09-23",
    source: "App Store",
    issueIds: ["mobile-perf"],
  },
  {
    id: "f-1011",
    text: "Great range and prices, but the app feels heavy on mobile data.",
    industry: "ecommerce",
    rating: 3,
    sentiment: "neutral",
    date: "2026-09-16",
    source: "App Store",
    issueIds: ["mobile-perf"],
  },
  {
    id: "f-1012",
    text: "On my phone the pay button sits under the bottom bar and I physically cannot tap it.",
    industry: "ecommerce",
    rating: 1,
    sentiment: "negative",
    date: "2026-09-25",
    source: "App Store",
    issueIds: ["checkout-mobile-ui"],
  },
  {
    id: "f-1013",
    text: "Latest update broke the checkout layout on my older phone.",
    industry: "ecommerce",
    rating: 2,
    sentiment: "negative",
    date: "2026-09-25",
    source: "App Store",
    issueIds: ["checkout-mobile-ui"],
  },
  {
    id: "f-1014",
    text: "Wine glasses arrived with two broken. Box was fine on the outside, no padding inside.",
    industry: "ecommerce",
    rating: 2,
    sentiment: "negative",
    date: "2026-09-12",
    source: "Web review",
    issueIds: ["packaging-damage"],
  },
  {
    id: "f-1015",
    text: "New packaging is much sturdier, my ceramics arrived perfectly this time.",
    industry: "ecommerce",
    rating: 5,
    sentiment: "positive",
    date: "2026-09-15",
    source: "Web review",
    issueIds: ["packaging-damage"],
  },
  {
    id: "f-1016",
    text: "Fast shipping, item exactly as described, and the packaging was genuinely nice to open.",
    industry: "ecommerce",
    rating: 5,
    sentiment: "positive",
    date: "2026-09-22",
    source: "Web review",
    issueIds: [],
  },
  {
    id: "f-1017",
    text: "Customer service sorted my sizing question in minutes. Really good experience.",
    industry: "ecommerce",
    rating: 5,
    sentiment: "positive",
    date: "2026-09-20",
    source: "Support ticket",
    issueIds: [],
  },
  {
    id: "f-2001",
    text: "Host said twenty minutes for a table, we waited almost an hour with no update.",
    industry: "restaurant",
    rating: 1,
    sentiment: "negative",
    date: "2026-09-24",
    source: "Google review",
    issueIds: ["wait-times"],
  },
  {
    id: "f-2002",
    text: "Long wait but they texted us twice and gave us a spot at the bar, so it was fine.",
    industry: "restaurant",
    rating: 4,
    sentiment: "positive",
    date: "2026-09-23",
    source: "Google review",
    issueIds: ["wait-times"],
  },
  {
    id: "f-2003",
    text: "Friday nights are unmanageable here. The queue estimate is basically fiction.",
    industry: "restaurant",
    rating: 2,
    sentiment: "negative",
    date: "2026-09-21",
    source: "Google review",
    issueIds: ["wait-times", "staff-attentiveness"],
  },
  {
    id: "f-2004",
    text: "Waited twenty five minutes just to get the bill, food itself was excellent.",
    industry: "restaurant",
    rating: 3,
    sentiment: "neutral",
    date: "2026-09-22",
    source: "In-app survey",
    issueIds: ["staff-attentiveness"],
  },
  {
    id: "f-2005",
    text: "Our server Maja was brilliant, but the room was clearly understaffed.",
    industry: "restaurant",
    rating: 3,
    sentiment: "neutral",
    date: "2026-09-19",
    source: "In-app survey",
    issueIds: ["staff-attentiveness"],
  },
  {
    id: "f-2006",
    text: "Missing both sides and a drink from a forty pound family order. Refund request went nowhere.",
    industry: "restaurant",
    rating: 1,
    sentiment: "negative",
    date: "2026-09-24",
    source: "Delivery app",
    issueIds: ["order-accuracy"],
  },
  {
    id: "f-2007",
    text: "Second time in a row the kids meals were wrong. Mains are always right, extras never are.",
    industry: "restaurant",
    rating: 2,
    sentiment: "negative",
    date: "2026-09-20",
    source: "Delivery app",
    issueIds: ["order-accuracy"],
  },
  {
    id: "f-2008",
    text: "Order was complete and hot for once. Please keep whoever packed it.",
    industry: "restaurant",
    rating: 4,
    sentiment: "positive",
    date: "2026-09-18",
    source: "Delivery app",
    issueIds: ["order-accuracy", "cold-food"],
  },
  {
    id: "f-2009",
    text: "Portions in the evening are noticeably smaller than at lunch for the same price.",
    industry: "restaurant",
    rating: 2,
    sentiment: "negative",
    date: "2026-09-23",
    source: "Google review",
    issueIds: ["portion-consistency"],
  },
  {
    id: "f-2010",
    text: "Lovely food, though the pasta plate was half what we had last month.",
    industry: "restaurant",
    rating: 3,
    sentiment: "neutral",
    date: "2026-09-17",
    source: "In-app survey",
    issueIds: ["portion-consistency"],
  },
  {
    id: "f-2011",
    text: "Mains turned up lukewarm, like they had been sitting under a lamp for a while.",
    industry: "restaurant",
    rating: 2,
    sentiment: "negative",
    date: "2026-09-25",
    source: "Google review",
    issueIds: ["cold-food"],
  },
  {
    id: "f-2012",
    text: "Food was cold again at the new layout site. Such a shame, the kitchen is good.",
    industry: "restaurant",
    rating: 2,
    sentiment: "negative",
    date: "2026-09-24",
    source: "In-app survey",
    issueIds: ["cold-food"],
  },
  {
    id: "f-2013",
    text: "Kiosk would not apply my points balance and the staff could not override it.",
    industry: "restaurant",
    rating: 2,
    sentiment: "negative",
    date: "2026-09-25",
    source: "In-app survey",
    issueIds: ["loyalty-points"],
  },
  {
    id: "f-2014",
    text: "Two years of loyalty points and the new till says my account does not exist.",
    industry: "restaurant",
    rating: 1,
    sentiment: "negative",
    date: "2026-09-23",
    source: "Support ticket",
    issueIds: ["loyalty-points"],
  },
  {
    id: "f-2015",
    text: "Points finally worked after staff typed it in manually. Slow but sorted.",
    industry: "restaurant",
    rating: 3,
    sentiment: "neutral",
    date: "2026-09-22",
    source: "In-app survey",
    issueIds: ["loyalty-points"],
  },
  {
    id: "f-2016",
    text: "Best roast in the area and the staff remembered our usual table. Faultless.",
    industry: "restaurant",
    rating: 5,
    sentiment: "positive",
    date: "2026-09-21",
    source: "Google review",
    issueIds: [],
  },
  {
    id: "f-2017",
    text: "Booked online, seated instantly, food out in fifteen minutes. Exactly what we wanted.",
    industry: "restaurant",
    rating: 5,
    sentiment: "positive",
    date: "2026-09-19",
    source: "In-app survey",
    issueIds: [],
  },
  {
    id: "f-2018",
    text: "Nice atmosphere, slightly pricey for the portion but we would come back.",
    industry: "restaurant",
    rating: 4,
    sentiment: "positive",
    date: "2026-09-16",
    source: "Google review",
    issueIds: ["portion-consistency"],
  },
];

export const decisions: Decision[] = [
  {
    id: "d-1",
    problem:
      "Card payments silently fail at checkout during evening peak, and most customers never retry.",
    recommendedAction:
      "Extend the gateway timeout to 45s, show an explicit retry state, and auto-retry failed authorisations once.",
    evidence: [
      "289 mentions in 30 days, 94% negative",
      "Failure reports peak 19:00-22:00 across 12 merchants",
      "78% describe a spinning button with no error message",
    ],
    affectedFeedback: 289,
    impact: "high",
    impactNote: "Est. +18% completed checkouts at peak",
    relatedIssueId: "payment-timeouts",
  },
  {
    id: "d-2",
    problem:
      "The delivery promise at checkout is set from warehouse capacity, so it breaks in carrier-constrained postcodes.",
    recommendedAction:
      "Recalculate the promise from live carrier SLAs per postcode and send a proactive re-promise when a window is at risk.",
    evidence: [
      "231 mentions, 86% negative",
      "Concentrated in postcodes served by a single carrier",
      "Refund requests appear in 34% of the same threads",
    ],
    affectedFeedback: 231,
    impact: "high",
    impactNote: "Est. -25% late-delivery contacts",
    relatedIssueId: "delivery-late",
  },
  {
    id: "d-3",
    problem:
      "Host wait quotes are fixed numbers, so every busy service creates a broken expectation at the door.",
    recommendedAction:
      "Drive the quote from live table-turn data and SMS guests whenever the estimate slips by ten minutes or more.",
    evidence: [
      "204 mentions, 81% negative",
      "Quoted 20 min vs 41 min median on Friday evenings",
      "Guests who received an update left neutral rather than negative reviews",
    ],
    affectedFeedback: 204,
    impact: "high",
    impactNote: "Est. -31% wait-related complaints",
    relatedIssueId: "wait-times",
  },
  {
    id: "d-4",
    problem:
      "Large delivery orders are packed across two stations with no shared checklist, so extras go missing.",
    recommendedAction:
      "Print one consolidated pack checklist per order and scan each bag before courier hand-off.",
    evidence: [
      "176 mentions, 88% negative",
      "Missing items are sides and drinks, rarely mains",
      "Half of reports also mention a failed refund",
    ],
    affectedFeedback: 176,
    impact: "medium",
    impactNote: "Est. -40% missing-item refunds",
    relatedIssueId: "order-accuracy",
  },
  {
    id: "d-5",
    problem:
      "A legacy account identifier is not passed to the new kiosk client, so loyalty balances cannot be matched at tender.",
    recommendedAction:
      "Backfill the identifier mapping and allow manual point entry from the terminal in the meantime.",
    evidence: [
      "74 mentions but growing 96% week over week",
      "Only affects accounts created before the kiosk migration",
      "Failure happens in front of staff at payment",
    ],
    affectedFeedback: 74,
    impact: "medium",
    impactNote: "Est. -90% loyalty escalations",
    relatedIssueId: "loyalty-points",
  },
  {
    id: "d-6",
    problem:
      "Release 4.18 introduced a sticky footer that covers the pay button on short viewports.",
    recommendedAction:
      "Hotfix the safe-area inset and add a small-viewport regression check to the release pipeline.",
    evidence: [
      "61 mentions, up 212% since the 4.18 release",
      "All reports on screens narrower than 380px",
      "Sits directly on the revenue path",
    ],
    affectedFeedback: 61,
    impact: "high",
    impactNote: "Unblocks checkout for small-screen traffic",
    relatedIssueId: "checkout-mobile-ui",
  },
  {
    id: "d-7",
    problem:
      "Customers contact support about returns because nothing confirms the parcel was received.",
    recommendedAction:
      "Confirm receipt at warehouse scan and show a refund countdown on the order page.",
    evidence: [
      "138 mentions, top driver of support contacts",
      "Expected refund 3 days, actual median 9 days",
      "Trend already down 6% after the label fix",
    ],
    affectedFeedback: 138,
    impact: "medium",
    impactNote: "Est. -22% return-status tickets",
    relatedIssueId: "return-flow",
  },
  {
    id: "d-8",
    problem:
      "Section sizes are planned for ordering, leaving the payment phase under-covered at peak.",
    recommendedAction:
      "Add a roaming payment runner during peak and enable pay-at-table from the QR menu.",
    evidence: [
      "112 mentions, 66% negative",
      "Waits are for the bill, not the food",
      "Positive reviews name servers, negatives name the room",
    ],
    affectedFeedback: 112,
    impact: "low",
    impactNote: "Est. +0.3 stars on service scores",
    relatedIssueId: "staff-attentiveness",
  },
];

export const crossThemes: CrossTheme[] = [
  {
    theme: "Delivery",
    ecommerceMentions: 278,
    restaurantMentions: 141,
    sharedPattern:
      "In both domains the complaint is the broken promise, not the duration. Accurate estimates outperform fast ones.",
    commonIssueIds: ["delivery-late", "cold-food"],
  },
  {
    theme: "Payment",
    ecommerceMentions: 289,
    restaurantMentions: 74,
    sharedPattern:
      "Failures happen at tender time with no recoverable path, so the customer experiences them as rejection.",
    commonIssueIds: ["payment-timeouts", "loyalty-points"],
  },
  {
    theme: "Waiting time",
    ecommerceMentions: 121,
    restaurantMentions: 204,
    sharedPattern:
      "Unacknowledged waiting is punished twice as hard as acknowledged waiting, online and in the room.",
    commonIssueIds: ["wait-times", "mobile-perf"],
  },
  {
    theme: "Service quality",
    ecommerceMentions: 138,
    restaurantMentions: 112,
    sharedPattern:
      "Customers forgive the failure but not the silence. Proactive contact converts negative sentiment to neutral.",
    commonIssueIds: ["return-flow", "staff-attentiveness"],
  },
  {
    theme: "Accuracy",
    ecommerceMentions: 47,
    restaurantMentions: 176,
    sharedPattern:
      "Errors cluster at the final assembly step in both domains, where no single checklist owns the whole order.",
    commonIssueIds: ["packaging-damage", "order-accuracy"],
  },
];

function buildTrend(): TrendPoint[] {
  const positive = [
    61, 63, 62, 65, 64, 67, 66, 69, 68, 70, 69, 72, 71, 73, 72, 74, 73, 75, 74,
    76, 75, 77, 76, 78, 77, 79, 78, 80, 79, 81,
  ];
  const negative = [
    28, 27, 29, 28, 30, 29, 31, 30, 32, 31, 30, 32, 31, 33, 32, 34, 33, 32, 34,
    33, 35, 34, 33, 35, 34, 36, 35, 34, 36, 35,
  ];
  return positive.map((p, i) => ({
    date: new Date(Date.UTC(2026, 7, 27 + i)).toISOString().slice(0, 10),
    positive: p,
    negative: negative[i],
  }));
}

export const sentimentTrend: TrendPoint[] = buildTrend();
