/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CrossDomainInsightsRouteImport } from './routes/cross-domain-insights'
import { Route as FeedbackExplorerRouteImport } from './routes/feedback-explorer'
import { Route as IssuesRouteImport } from './routes/issues'
import { Route as ProductDecisionsRouteImport } from './routes/product-decisions'
import { Route as UploadFeedbackRouteImport } from './routes/upload-feedback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrossDomainInsightsRoute = CrossDomainInsightsRouteImport.update({
  id: '/cross-domain-insights',
  path: '/cross-domain-insights',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackExplorerRoute = FeedbackExplorerRouteImport.update({
  id: '/feedback-explorer',
  path: '/feedback-explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesRoute = IssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductDecisionsRoute = ProductDecisionsRouteImport.update({
  id: '/product-decisions',
  path: '/product-decisions',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadFeedbackRoute = UploadFeedbackRouteImport.update({
  id: '/upload-feedback',
  path: '/upload-feedback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cross-domain-insights': typeof CrossDomainInsightsRoute
  '/feedback-explorer': typeof FeedbackExplorerRoute
  '/issues': typeof IssuesRoute
  '/product-decisions': typeof ProductDecisionsRoute
  '/upload-feedback': typeof UploadFeedbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cross-domain-insights': typeof CrossDomainInsightsRoute
  '/feedback-explorer': typeof FeedbackExplorerRoute
  '/issues': typeof IssuesRoute
  '/product-decisions': typeof ProductDecisionsRoute
  '/upload-feedback': typeof UploadFeedbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cross-domain-insights': typeof CrossDomainInsightsRoute
  '/feedback-explorer': typeof FeedbackExplorerRoute
  '/issues': typeof IssuesRoute
  '/product-decisions': typeof ProductDecisionsRoute
  '/upload-feedback': typeof UploadFeedbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cross-domain-insights'
    | '/feedback-explorer'
    | '/issues'
    | '/product-decisions'
    | '/upload-feedback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cross-domain-insights'
    | '/feedback-explorer'
    | '/issues'
    | '/product-decisions'
    | '/upload-feedback'
  id:
    | '__root__'
    | '/'
    | '/cross-domain-insights'
    | '/feedback-explorer'
    | '/issues'
    | '/product-decisions'
    | '/upload-feedback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CrossDomainInsightsRoute: typeof CrossDomainInsightsRoute
  FeedbackExplorerRoute: typeof FeedbackExplorerRoute
  IssuesRoute: typeof IssuesRoute
  ProductDecisionsRoute: typeof ProductDecisionsRoute
  UploadFeedbackRoute: typeof UploadFeedbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cross-domain-insights': {
      id: '/cross-domain-insights'
      path: '/cross-domain-insights'
      fullPath: '/cross-domain-insights'
      preLoaderRoute: typeof CrossDomainInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback-explorer': {
      id: '/feedback-explorer'
      path: '/feedback-explorer'
      fullPath: '/feedback-explorer'
      preLoaderRoute: typeof FeedbackExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues': {
      id: '/issues'
      path: '/issues'
      fullPath: '/issues'
      preLoaderRoute: typeof IssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product-decisions': {
      id: '/product-decisions'
      path: '/product-decisions'
      fullPath: '/product-decisions'
      preLoaderRoute: typeof ProductDecisionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload-feedback': {
      id: '/upload-feedback'
      path: '/upload-feedback'
      fullPath: '/upload-feedback'
      preLoaderRoute: typeof UploadFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CrossDomainInsightsRoute: CrossDomainInsightsRoute,
  FeedbackExplorerRoute: FeedbackExplorerRoute,
  IssuesRoute: IssuesRoute,
  ProductDecisionsRoute: ProductDecisionsRoute,
  UploadFeedbackRoute: UploadFeedbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
