/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FeedbackExplorerRouteImport } from './routes/feedback-explorer'
import { Route as UploadFeedbackRouteImport } from './routes/upload-feedback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackExplorerRoute = FeedbackExplorerRouteImport.update({
  id: '/feedback-explorer',
  path: '/feedback-explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadFeedbackRoute = UploadFeedbackRouteImport.update({
  id: '/upload-feedback',
  path: '/upload-feedback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/feedback-explorer': typeof FeedbackExplorerRoute
  '/upload-feedback': typeof UploadFeedbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/feedback-explorer': typeof FeedbackExplorerRoute
  '/upload-feedback': typeof UploadFeedbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/feedback-explorer': typeof FeedbackExplorerRoute
  '/upload-feedback': typeof UploadFeedbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/feedback-explorer' | '/upload-feedback'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/feedback-explorer' | '/upload-feedback'
  id: '__root__' | '/' | '/feedback-explorer' | '/upload-feedback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FeedbackExplorerRoute: typeof FeedbackExplorerRoute
  UploadFeedbackRoute: typeof UploadFeedbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback-explorer': {
      id: '/feedback-explorer'
      path: '/feedback-explorer'
      fullPath: '/feedback-explorer'
      preLoaderRoute: typeof FeedbackExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload-feedback': {
      id: '/upload-feedback'
      path: '/upload-feedback'
      fullPath: '/upload-feedback'
      preLoaderRoute: typeof UploadFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FeedbackExplorerRoute: FeedbackExplorerRoute,
  UploadFeedbackRoute: UploadFeedbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
